// <auto-generated />
using System;
using GameNLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameNLog.Migrations
{
    [DbContext(typeof(GameNLogContext))]
    partial class GameNLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameNLog.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GameNLog.Models.Cover", b =>
                {
                    b.Property<int>("CoverID")
                        .HasColumnType("integer");

                    b.Property<string>("ImageID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CoverID");

                    b.ToTable("Covers");
                });

            modelBuilder.Entity("GameNLog.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("CoverID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameID");

                    b.HasIndex("CoverID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameNLog.Models.GameGenre", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("GenreID")
                        .HasColumnType("integer");

                    b.HasKey("GameID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameNLog.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformID")
                        .HasColumnType("integer");

                    b.HasKey("GameID", "PlatformID");

                    b.HasIndex("PlatformID");

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameNLog.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GameNLog.Models.InvolvedCompany", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.HasKey("GameID", "CompanyID");

                    b.HasIndex("CompanyID");

                    b.ToTable("InvolvedCompanies");
                });

            modelBuilder.Entity("GameNLog.Models.Platform", b =>
                {
                    b.Property<int>("PlatformID")
                        .HasColumnType("integer");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlatformID");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GameNLog.Models.PlayedGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayedAt")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("GameID", "UserID")
                        .IsUnique();

                    b.ToTable("PlayedGames");
                });

            modelBuilder.Entity("GameNLog.Models.PlayedGameReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PlayedGameID")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("ReviewID");

                    b.HasIndex("PlayedGameID");

                    b.ToTable("PlayedGameReviews");
                });

            modelBuilder.Entity("GameNLog.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameNLog.Models.Game", b =>
                {
                    b.HasOne("GameNLog.Models.Cover", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("GameNLog.Models.GameGenre", b =>
                {
                    b.HasOne("GameNLog.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameNLog.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameNLog.Models.GamePlatform", b =>
                {
                    b.HasOne("GameNLog.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameNLog.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameNLog.Models.InvolvedCompany", b =>
                {
                    b.HasOne("GameNLog.Models.Company", "Company")
                        .WithMany("InvolvedCompanies")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameNLog.Models.Game", "Game")
                        .WithMany("InvolvedCompanies")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameNLog.Models.PlayedGame", b =>
                {
                    b.HasOne("GameNLog.Models.Game", null)
                        .WithMany("PlayedGames")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameNLog.Models.User", null)
                        .WithMany("PlayedGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameNLog.Models.PlayedGameReview", b =>
                {
                    b.HasOne("GameNLog.Models.PlayedGame", "PlayedGame")
                        .WithMany("Reviews")
                        .HasForeignKey("PlayedGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayedGame");
                });

            modelBuilder.Entity("GameNLog.Models.Company", b =>
                {
                    b.Navigation("InvolvedCompanies");
                });

            modelBuilder.Entity("GameNLog.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("InvolvedCompanies");

                    b.Navigation("PlayedGames");
                });

            modelBuilder.Entity("GameNLog.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("GameNLog.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameNLog.Models.PlayedGame", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GameNLog.Models.User", b =>
                {
                    b.Navigation("PlayedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
